### ISSUE TITLE
[Analysis] AttributeError on running simple analysis

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#18] opened 2018-06-11 15:09 UTC
### Problem
I use the test layers from "Add test layers" button, and I tried to run analysis for:
- Exposure: Census
- Hazard: Continuous Flood
- Aggregation: Entire Area

I got this error:

```
Problem
The following problem(s) were encountered whilst running the analysis.

AttributeError
Suggestion
You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details
These additional details were reported when the problem occurred.

'InvalidLayerError' object has no attribute 'message'
Diagnostics

In file "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/impact_function/impact_function.py", line 1448, in run self._run()
In file "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/utilities/profiling.py", line 126, in with_profiling ret = fn(*args, **kwargs)
In file "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/impact_function/impact_function.py", line 1652, in _run self.hazard_preparation()
In file "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/utilities/profiling.py", line 126, in with_profiling ret = fn(*args, **kwargs)
In file "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/impact_function/impact_function.py", line 2149, in hazard_preparation self.hazard = clip_by_extent(self.hazard, extent)
In file "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/utilities/profiling.py", line 126, in with_profiling ret = fn(*args, **kwargs)
In file "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gis/raster/clip_bounding_box.py", line 125, in clip_by_extent LOGGER.exception(get_error_message(e).to_text())
In file "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/utilities/utilities.py", line 97, in get_error_message suggestion = exception.message
```

It runs fine in QGIS 2.18/InaSAFE v4.4

### Environment
* InaSAFE : master
* QGIS : master
* OS : MacOS

* Data used : see above
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist: 

* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution

**Comment by ismailsunni** [comment] 2018-06-12 04:14
Checking other combination, it seems it will occur if the hazard is raster

**Comment by elpaso** [comment] 2018-06-12 13:07
I cannot reproduce on Linux with current QGIS master

**Comment by ismailsunni** [comment] 2018-06-13 02:48
Hmm, I will try to build the latest QGIS (mine is from Monday), and see if I can replicate it again

**Comment by ismailsunni** [comment] 2018-06-13 03:18
Ouch, I still got the same error here, perhaps OS specific? Or something wrong in my QGIS build?

**Comment by nyalldawson** [comment] 2018-06-13 09:21
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/3b6f3d31a1e403f69bef61324e7ffe1555772c0b

**Closed as completed by nyalldawson** 2018-06-13 09:21 UTC

**Comment by ismailsunni** [comment] 2018-06-19 11:02
Checked.
