### ISSUE TITLE
[Keyword Wizard] Back Button Seems Disabled

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#23] opened 2018-06-12 06:30 UTC
### Problem
Seems similar with https://github.com/north-road/inasafe/issues/22

<img width="1071" alt="screen shot 2018-06-12 at 13 28 37" src="https://user-images.githubusercontent.com/1421861/41273695-af509cb2-6e44-11e8-9b1d-408bcf8c101b.png">

**Comment by ismailsunni** [comment] 2018-06-12 06:44
Similar problem:
- Click show help
- The back and next button seems enabled (it should be disabled)
- Change focus, and re-focus, it becomes disabled
- Hide the help, the button seems disabled (it should be enabled)
- Change focus, and re-focus, it becomes enabled

**Comment by nyalldawson** [comment] 2018-06-15 03:26
Duplicate of #22

**Closed as completed by nyalldawson** 2018-06-15 03:26 UTC
