### ISSUE TITLE
[Keyword Wizard] Strange text in multi classification step

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#25] opened 2018-06-12 06:41 UTC
### Problem
To replicate:
- Load test layers
- Open keyword wizard for Flood Polygon
- Click next until multi-classification step
- Click edit button
- It will show unexpected text below the drag and drop area
- If you click save, there is unwanted text above Value Maps area
See gif below:
![strange_text_in_keyword_wizard](https://user-images.githubusercontent.com/1421861/41274034-1e42f97a-6e46-11e8-8a36-2af1549c1a93.gif)

Notes:
- Move my double finger (scroll action), will fix it immediately

**Comment by nyalldawson** [comment] 2018-06-15 02:10
Not reproducible outside of OSX

**Comment by nyalldawson** [comment] 2018-06-15 03:22
Actually this is a duplicate of #24

**Closed as completed by nyalldawson** 2018-06-15 03:22 UTC
Labels: Upstream Qt OSX bug

**Comment by ismailsunni** [comment] 2018-06-19 10:08
Checked.
